/* Generated By:JavaCC: Do not edit this line. KML_lexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KML_lexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int LETRAS = 6;
  /** RegularExpression Id. */
  int MAYUSCULAS = 7;
  /** RegularExpression Id. */
  int MINOMBRE = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMERO>",
    "<LETRAS>",
    "<MAYUSCULAS>",
    "<MINOMBRE>",
    "<FLOAT>",
  };

}
