/* Generated By:JavaCC: Do not edit this line. KML_lexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KML_lexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENCABEZADO = 5;
  /** RegularExpression Id. */
  int NUMEROV = 6;
  /** RegularExpression Id. */
  int DECLARACION = 7;
  /** RegularExpression Id. */
  int ABRIR_PLACEMARK = 8;
  /** RegularExpression Id. */
  int NOMBRE = 9;
  /** RegularExpression Id. */
  int DESCRIPCION = 10;
  /** RegularExpression Id. */
  int LINE_STRING_OPEN = 11;
  /** RegularExpression Id. */
  int OPEN_COORDINATES = 12;
  /** RegularExpression Id. */
  int COORDENADA = 13;
  /** RegularExpression Id. */
  int LONGITUD = 14;
  /** RegularExpression Id. */
  int LATITUD = 15;
  /** RegularExpression Id. */
  int ELEVACION = 16;
  /** RegularExpression Id. */
  int CLOSE_COORDINATES = 17;
  /** RegularExpression Id. */
  int LINE_STRING_CLOSE = 18;
  /** RegularExpression Id. */
  int CERRAR_PLACEMARK = 19;
  /** RegularExpression Id. */
  int CERRAR_KML = 20;
  /** RegularExpression Id. */
  int NUMERO = 21;
  /** RegularExpression Id. */
  int LETRAS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ENCABEZADO>",
    "<NUMEROV>",
    "\"<kml xmlns=http://www.opengis.net/kml/2.2>\"",
    "\"<Placemark>\"",
    "<NOMBRE>",
    "<DESCRIPCION>",
    "\"<LineString>\"",
    "\"<coordinates>\"",
    "<COORDENADA>",
    "<LONGITUD>",
    "<LATITUD>",
    "<ELEVACION>",
    "\"</coordinates>\"",
    "\"</LineString>\"",
    "\"</Placemark>\"",
    "\"</kml>\"",
    "<NUMERO>",
    "<LETRAS>",
  };

}
